name:                 etz-chaim-sim
version:              0.1.0.0
visibility:           public
id:                   etz-chaim-sim-0.1.0.0-inplace
key:                  etz-chaim-sim-0.1.0.0-inplace
license:              MIT
maintainer:           team@etzchaim.org
author:               EtzChaim Team
abi:                  inplace
exposed:              True
exposed-modules:
    Engine.FFI.AgdaEinSof Engine.FFI.AgdaIgulimYosher
    Engine.FFI.AgdaTzimtzum Engine.Kabbalah.LightAlgebra
    Engine.Math.Cardinal Engine.Math.Ordinal Engine.Runner.BasicRunner
    Engine.Runner.CliRunner Engine.Runner.RunnerState
    Engine.Scenarios.Library Engine.Scenarios.Stage4Logs
    Engine.Simulation.AkPreparation Engine.Simulation.Core
    Engine.Simulation.Hishtalshelut Engine.Simulation.Kav
    Engine.Templates.NewScenario Engine.Types.BasicTypes
    Engine.Types.CoreTypes Engine.Types.LightTypes
    Engine.Types.Scenario Engine.Types.SimulationState

hidden-modules:       Paths_etz_chaim_sim
import-dirs:
    /workspace/dist-newstyle/build/x86_64-linux/ghc-9.6.7/etz-chaim-sim-0.1.0.0/build

library-dirs:
    /workspace/dist-newstyle/build/x86_64-linux/ghc-9.6.7/etz-chaim-sim-0.1.0.0/build

library-dirs-static:
    /workspace/dist-newstyle/build/x86_64-linux/ghc-9.6.7/etz-chaim-sim-0.1.0.0/build

dynamic-library-dirs:
    /workspace/dist-newstyle/build/x86_64-linux/ghc-9.6.7/etz-chaim-sim-0.1.0.0/build

data-dir:             /workspace/.
hs-libraries:         HSetz-chaim-sim-0.1.0.0-inplace
depends:
    aeson-2.2.3.0-e2278952af29a7bf695aedc3ed20b269e3119707fc3aa3e302a2a6b1c3cf0914
    base-4.18.3.0 bytestring-0.11.5.4 containers-0.6.7
    directory-1.3.8.5 filepath-1.4.301.0 process-1.6.19.0 stm-2.5.1.0
    text-2.0.2 time-1.12.2
    uuid-1.3.16-15103712f60eb90ea14e2331f05adb0d4660475b60bd9e58cbb18c12128ae2b2

haddock-interfaces:
    /workspace/dist-newstyle/build/x86_64-linux/ghc-9.6.7/etz-chaim-sim-0.1.0.0/doc/html/etz-chaim-sim/etz-chaim-sim.haddock

haddock-html:
    /workspace/dist-newstyle/build/x86_64-linux/ghc-9.6.7/etz-chaim-sim-0.1.0.0/doc/html/etz-chaim-sim
